config/routes.rb
Rails.application.routes.draw do
  root to: "agents#random_agent"

  resources :agents do
    resources :uploaded_transactions
    post '/import_from_csv', to: 'uploaded_transactions#import_from_csv'
  end
end

app/models/agent.rb
class Agent < ApplicationRecord
  has_many :uploaded_seller_transactions, class_name: "UploadedTransaction", foreign_key: :listing_agent_id
  has_many :uploaded_buyer_transactions, class_name: "UploadedTransaction", foreign_key: :selling_agent_id

  def all_transactions
    UploadedTransaction.where("listing_agent_id = ? OR selling_agent_id = ?", id, id)
  end

  def recent_transactions
    all_transactions.where("selling_date > ?", 6.months.ago)
  end

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/uploaded_transaction.rb
class UploadedTransaction < ApplicationRecord
  require 'csv'
  paginates_per 12

  belongs_to :listing_agent, required: false, class_name: "Agent"
  belongs_to :selling_agent, required: false, class_name: "Agent"

  scope :single_family_homes, -> { where(property_type: "single_family_home") }
  scope :sold, -> { where(status: "sold") }

  validates :address, :zip, :selling_date, presence: true
  validates_uniqueness_of :address, scope: [:zip, :selling_date],
    message: "with this property, zip, and selling date already exists."

  def full_address
    "#{address}, #{city}, #{state} #{zip}"
  end

  def self.import_from_csv(file)
    successes = 0, 0
    CSV.foreach(file.path, headers: true) do |row|
      row = row.to_hash
      transaction = find_or_initialize_by(
        address: row["address"],
        zip: row["zip"],
        selling_date: row["selling_date"]
      )
      create(row) if transaction.new_record?
    end
  end
end

app/controllers/agents_controller.rb
class AgentsController < ApplicationController
  def show
    @agent = Agent.find(params[:id])
    @uploaded_transactions = @agent.all_transactions.page(params[:page])
  end

  def random_agent
    redirect_to agent_path(Agent.all.sample)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/uploaded_transactions_controller.rb
class UploadedTransactionsController < ApplicationController
  def new
    @agent = Agent.find(params[:agent_id])
    @uploaded_transaction = @agent.uploaded_seller_transactions.new
  end

  def create
    @agent = Agent.find(params[:agent_id])
    @uploaded_transaction = @agent.uploaded_seller_transactions.create(uploaded_transaction_params)
    if @uploaded_transaction.save
      redirect_to agent_path(@agent), notice: "Transaction saved!"
    else
      render "new"
    end
  end

  def import_from_csv
    UploadedTransaction.import_from_csv(params[:file])
    redirect_to agent_path(params[:agent_id]), notice: "File imported!"
  end

  private

  def uploaded_transaction_params
    params.require(:uploaded_transaction).permit(:address, :city, :state, :zip, :listing_agent, :listing_price, :listing_date, :selling_price, :selling_agent, :selling_date, :status, :property_type)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/agents/show.html.slim
h1 = @agent.full_name
p = @agent.bio

= link_to "Add Transaction", new_agent_uploaded_transaction_path(@agent), class: "btn btn-primary"

= form_with url: agent_import_from_csv_path(@agent) do |f|
  = f.file_field :file, class: "btn"
  = f.submit "Import CSV", class: "btn btn-success"

h3 Recent Transactions
table.container
  thead
    tr
      th Address
      th Listed
      th Listing Price
      th Sold
      th Selling Price
      th
  tbody
    - @uploaded_transactions.each do |uploaded_transaction|
      tr
        td = uploaded_transaction.full_address
        td = uploaded_transaction.listing_date
        td = uploaded_transaction.listing_price
        td = uploaded_transaction.selling_date
        td = uploaded_transaction.selling_price
.container.pagination.justify-content-center = paginate @uploaded_transactions

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Uploaded Transactions Manager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <a class="navbar-brand" href="#">HomeLight</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
             <li class="nav-item dropdown active">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Agents</a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <% Agent.all.each do |agent| %>
                  <a class="dropdown-item" href="<%= agent_path(agent) %>"><%= agent.full_name %></a>
                <% end %>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, class: name %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/uploaded_transactions/new.html.slim
h1.text-center Create a Transaction

- if @uploaded_transaction.errors.any?
  #error_explanation
    h5 = pluralize(@uploaded_transaction.errors.count, "error") + " prohibited this article from being saved:"
    ul
      - @uploaded_transaction.errors.full_messages.each do |msg|
        li.alert.alert-danger = msg

= form_for [@agent, @uploaded_transaction] do |f|
  .row
    .col-md-6
      .form-group
        = f.label :address
        = f.text_field :address, class: "form-control input-lg", required: true
      .form-group
        = f.label :city
        = f.text_field :city, class: "form-control"
      .form-group
        = f.label :state
        = f.text_field :state, class: "form-control"
      .form-group
        = f.label :zip
        = f.text_field :zip, class: "form-control", required: true
      .form-group.form-check
        = f.check_box :selling_agent_id, { class: "form-check-input", checked: false }, 
            check_value = @agent.id, unchecked_value = "" 
        = f.label :selling_agent_id, "check if you are the selling agent", class: "form-check-label"
      .form-group.form-check
        = f.check_box :listing_agent_id, { class: "form-check-input", checked: false },
            checked_value = @agent.id, unchecked_value = ""
        = f.label :listing_agent_id, "check if you are the listing agent", class: "form-check-label"
    .col-md-6
      .form-group
        = f.label :listing_date
        = f.date_field :listing_date, class: "form-control"
      .form-group
        = f.label :listing_price
        = f.text_field :listing_price, class: "form-control"
      .form-group
        = f.label :selling_date
        = f.date_field :selling_date, class: "form-control", required: true
      .form-group
        = f.label :selling_price
        = f.text_field :selling_price, class: "form-control"
      .form-group
        = f.label :status
        = f.select :status, 
            %w(sold pending closed cancelled expired active), 
            {}, 
            class: "form-control"
      .form-group
        = f.label :property_type
        = f.select :property_type, 
            %w(condo single_family_home multi_family_home commercial mobile_home land),
            {}, 
            class: "form-control"
    = f.submit "Save", class: "btn btn-primary btn-lg"